# Generated by Django 3.2.7 on 2023-05-03 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0004_auto_20230503_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participated_event', to='my_data.event'),
        ),
    ]
