# Generated by Django 3.2.7 on 2023-05-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0005_participants_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participated_event', to='my_data.event'),
            preserve_default=False,
        ),
    ]
