# Generated by Django 3.2.7 on 2023-05-03 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0006_alter_participants_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.AlterField(
            model_name='participants',
            name='participation_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_data.participationcategory'),
        ),
    ]
