# Generated by Django 3.2.12 on 2023-05-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_data', '0008_auto_20230503_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='person_responsible',
        ),
    ]
