# Generated by Django 3.2.7 on 2023-05-08 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_data', '0009_remove_participants_person_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('janajatti', 'Janajatti'), ('dalit', 'Dalit'), ('muslim', 'Muslim'), ('brahmin/kshetri', 'Brahmin/Kshetri'), ('others', 'Others')], max_length=500),
        ),
        migrations.AlterField(
            model_name='participants',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('trans_sex', 'trans_sex')], default='male', max_length=500),
        ),
        migrations.AlterField(
            model_name='participants',
            name='step1_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_a', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participants',
            name='step2_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participants',
            name='step3_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role_c', to=settings.AUTH_USER_MODEL),
        ),
    ]
